import numpy as np
one_array = np.ones((2,3))
zero_array = np.zeros((2,3))
empty_array = np.empty((2,3))
print("ones array: \n",one_array,"\nzeros array:\n",zero_array,"\nempty array:\n",empty_array)
arr=np.array([[1,2,3],[4,5,6]])
print("Shape of this array: ",arr.shape)
reshape=arr.reshape(3,2)
print("Reshaped array:\n",reshape)
arr1=np.array([1,2,3])
copy_arr1=arr1.copy()
view_arr1=arr1.view()
print("copy: ",copy_arr1)
print("view: ",view_arr1)
arr2=np.array([1,2])
arr3=np.array([3,4])
concatenated=np.concatenate((arr1,arr2))
print("concatenated array: ",concatenated)
arr4 = np.array([5,2,9,1])
print("Sorted array: ",np.sort(arr4))